import type { Scale, ScaleItem, ResponseMapping } from "./types"

export const SCALES: Scale[] = [
  {
    id: "bdi-ii",
    name: "Beck Depression Inventory-II",
    description: "A 21-item self-report measure of depression severity",
    totalItems: 21,
    scoringType: "sum",
    responseFormat: "numeric",
    minScore: 0,
    maxScore: 63,
    expectedRange: "0-3",
    isPublic: true,
    isVerified: true,
    citation: "Beck, A. T., Steer, R. A., & Brown, G. K. (1996). Manual for the Beck Depression Inventory-II.",
    interpretationRanges: [
      {
        id: "bdi-minimal",
        scaleId: "bdi-ii",
        minScore: 0,
        maxScore: 13,
        severity: "Minimal",
        description: "Minimal depression",
        color: "#10b981",
      },
      {
        id: "bdi-mild",
        scaleId: "bdi-ii",
        minScore: 14,
        maxScore: 19,
        severity: "Mild",
        description: "Mild depression",
        color: "#f59e0b",
      },
      {
        id: "bdi-moderate",
        scaleId: "bdi-ii",
        minScore: 20,
        maxScore: 28,
        severity: "Moderate",
        description: "Moderate depression",
        color: "#f97316",
      },
      {
        id: "bdi-severe",
        scaleId: "bdi-ii",
        minScore: 29,
        maxScore: 63,
        severity: "Severe",
        description: "Severe depression",
        color: "#dc2626",
      },
    ],
  },
  {
    id: "gad-7",
    name: "Generalized Anxiety Disorder 7-item",
    description: "A 7-item measure of anxiety symptoms",
    totalItems: 7,
    scoringType: "sum",
    responseFormat: "text",
    minScore: 0,
    maxScore: 21,
    expectedRange: "0-3",
    isPublic: true,
    isVerified: true,
    citation: "Spitzer, R. L., Kroenke, K., Williams, J. B., & Löwe, B. (2006).",
    interpretationRanges: [
      {
        id: "gad-minimal",
        scaleId: "gad-7",
        minScore: 0,
        maxScore: 4,
        severity: "Minimal",
        description: "Minimal anxiety",
        color: "#10b981",
      },
      {
        id: "gad-mild",
        scaleId: "gad-7",
        minScore: 5,
        maxScore: 9,
        severity: "Mild",
        description: "Mild anxiety",
        color: "#f59e0b",
      },
      {
        id: "gad-moderate",
        scaleId: "gad-7",
        minScore: 10,
        maxScore: 14,
        severity: "Moderate",
        description: "Moderate anxiety",
        color: "#f97316",
      },
      {
        id: "gad-severe",
        scaleId: "gad-7",
        minScore: 15,
        maxScore: 21,
        severity: "Severe",
        description: "Severe anxiety",
        color: "#dc2626",
      },
    ],
  },
  {
    id: "phq-9",
    name: "Patient Health Questionnaire-9",
    description: "A 9-item depression screening and severity measure",
    totalItems: 9,
    scoringType: "sum",
    responseFormat: "text",
    minScore: 0,
    maxScore: 27,
    expectedRange: "0-3",
    isPublic: true,
    isVerified: true,
    citation: "Kroenke, K., Spitzer, R. L., & Williams, J. B. (2001).",
    interpretationRanges: [
      {
        id: "phq-minimal",
        scaleId: "phq-9",
        minScore: 0,
        maxScore: 4,
        severity: "Minimal",
        description: "Minimal depression",
        color: "#10b981",
      },
      {
        id: "phq-mild",
        scaleId: "phq-9",
        minScore: 5,
        maxScore: 9,
        severity: "Mild",
        description: "Mild depression",
        color: "#f59e0b",
      },
      {
        id: "phq-moderate",
        scaleId: "phq-9",
        minScore: 10,
        maxScore: 14,
        severity: "Moderate",
        description: "Moderate depression",
        color: "#f97316",
      },
      {
        id: "phq-moderately-severe",
        scaleId: "phq-9",
        minScore: 15,
        maxScore: 19,
        severity: "Moderately Severe",
        description: "Moderately severe depression",
        color: "#ea580c",
      },
      {
        id: "phq-severe",
        scaleId: "phq-9",
        minScore: 20,
        maxScore: 27,
        severity: "Severe",
        description: "Severe depression",
        color: "#dc2626",
      },
    ],
  },
  {
    id: "big-five",
    name: "Big Five Personality Inventory",
    description: "A comprehensive personality assessment measuring five major dimensions",
    totalItems: 50,
    scoringType: "average",
    responseFormat: "text",
    minScore: 1.0,
    maxScore: 5.0,
    expectedRange: "1-5",
    isPublic: true,
    isVerified: true,
    citation: "John, O. P., & Srivastava, S. (1999). The Big Five trait taxonomy.",
    interpretationRanges: [
      {
        id: "bf-low",
        scaleId: "big-five",
        minScore: 1.0,
        maxScore: 2.5,
        severity: "Low",
        description: "Below average trait expression",
        color: "#3b82f6",
      },
      {
        id: "bf-average",
        scaleId: "big-five",
        minScore: 2.6,
        maxScore: 3.4,
        severity: "Average",
        description: "Average trait expression",
        color: "#10b981",
      },
      {
        id: "bf-high",
        scaleId: "big-five",
        minScore: 3.5,
        maxScore: 5.0,
        severity: "High",
        description: "Above average trait expression",
        color: "#f59e0b",
      },
    ],
  },
]

export const SCALE_ITEMS: ScaleItem[] = [
  // BDI-II Items (all 21 items)
  {
    id: "bdi-1",
    scaleId: "bdi-ii",
    itemNumber: 1,
    questionText: "Sadness",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-2",
    scaleId: "bdi-ii",
    itemNumber: 2,
    questionText: "Pessimism",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-3",
    scaleId: "bdi-ii",
    itemNumber: 3,
    questionText: "Past Failure",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-4",
    scaleId: "bdi-ii",
    itemNumber: 4,
    questionText: "Loss of Pleasure",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-5",
    scaleId: "bdi-ii",
    itemNumber: 5,
    questionText: "Guilty Feelings",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-6",
    scaleId: "bdi-ii",
    itemNumber: 6,
    questionText: "Punishment Feelings",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-7",
    scaleId: "bdi-ii",
    itemNumber: 7,
    questionText: "Self-Dislike",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-8",
    scaleId: "bdi-ii",
    itemNumber: 8,
    questionText: "Self-Criticalness",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-9",
    scaleId: "bdi-ii",
    itemNumber: 9,
    questionText: "Suicidal Thoughts or Wishes",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-10",
    scaleId: "bdi-ii",
    itemNumber: 10,
    questionText: "Crying",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-11",
    scaleId: "bdi-ii",
    itemNumber: 11,
    questionText: "Agitation",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-12",
    scaleId: "bdi-ii",
    itemNumber: 12,
    questionText: "Loss of Interest",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-13",
    scaleId: "bdi-ii",
    itemNumber: 13,
    questionText: "Indecisiveness",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-14",
    scaleId: "bdi-ii",
    itemNumber: 14,
    questionText: "Worthlessness",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-15",
    scaleId: "bdi-ii",
    itemNumber: 15,
    questionText: "Loss of Energy",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-16",
    scaleId: "bdi-ii",
    itemNumber: 16,
    questionText: "Changes in Sleeping Pattern",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-17",
    scaleId: "bdi-ii",
    itemNumber: 17,
    questionText: "Irritability",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-18",
    scaleId: "bdi-ii",
    itemNumber: 18,
    questionText: "Changes in Appetite",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-19",
    scaleId: "bdi-ii",
    itemNumber: 19,
    questionText: "Concentration Difficulty",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-20",
    scaleId: "bdi-ii",
    itemNumber: 20,
    questionText: "Tiredness or Fatigue",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  {
    id: "bdi-21",
    scaleId: "bdi-ii",
    itemNumber: 21,
    questionText: "Loss of Interest in Sex",
    responseType: "multiple_choice",
    isReverseCoded: false,
  },
  // GAD-7 Items (all 7 items)
  {
    id: "gad-1",
    scaleId: "gad-7",
    itemNumber: 1,
    questionText: "Feeling nervous, anxious, or on edge",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "gad-2",
    scaleId: "gad-7",
    itemNumber: 2,
    questionText: "Not being able to stop or control worrying",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "gad-3",
    scaleId: "gad-7",
    itemNumber: 3,
    questionText: "Worrying too much about different things",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "gad-4",
    scaleId: "gad-7",
    itemNumber: 4,
    questionText: "Trouble relaxing",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "gad-5",
    scaleId: "gad-7",
    itemNumber: 5,
    questionText: "Being so restless that it's hard to sit still",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "gad-6",
    scaleId: "gad-7",
    itemNumber: 6,
    questionText: "Becoming easily annoyed or irritable",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "gad-7",
    scaleId: "gad-7",
    itemNumber: 7,
    questionText: "Feeling afraid as if something awful might happen",
    responseType: "likert",
    isReverseCoded: false,
  },
  // PHQ-9 Items (all 9 items)
  {
    id: "phq-1",
    scaleId: "phq-9",
    itemNumber: 1,
    questionText: "Little interest or pleasure in doing things",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-2",
    scaleId: "phq-9",
    itemNumber: 2,
    questionText: "Feeling down, depressed, or hopeless",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-3",
    scaleId: "phq-9",
    itemNumber: 3,
    questionText: "Trouble falling or staying asleep, or sleeping too much",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-4",
    scaleId: "phq-9",
    itemNumber: 4,
    questionText: "Feeling tired or having little energy",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-5",
    scaleId: "phq-9",
    itemNumber: 5,
    questionText: "Poor appetite or overeating",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-6",
    scaleId: "phq-9",
    itemNumber: 6,
    questionText: "Feeling bad about yourself or that you are a failure",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-7",
    scaleId: "phq-9",
    itemNumber: 7,
    questionText: "Trouble concentrating on things",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-8",
    scaleId: "phq-9",
    itemNumber: 8,
    questionText: "Moving or speaking slowly or being fidgety or restless",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "phq-9",
    scaleId: "phq-9",
    itemNumber: 9,
    questionText: "Thoughts that you would be better off dead or hurting yourself",
    responseType: "likert",
    isReverseCoded: false,
  },
  // Big Five Items (sample)
  {
    id: "bf-1",
    scaleId: "big-five",
    itemNumber: 1,
    questionText: "I am the life of the party",
    responseType: "likert",
    isReverseCoded: false,
  },
  {
    id: "bf-2",
    scaleId: "big-five",
    itemNumber: 2,
    questionText: "I feel little concern for others",
    responseType: "likert",
    isReverseCoded: true,
  },
]

export const RESPONSE_MAPPINGS: ResponseMapping[] = [
  // GAD-7 and PHQ-9 Likert responses (0-3 scale)
  {
    id: "likert-0",
    scaleItemId: "gad-1",
    textResponse: "Not at all",
    numericValue: 0,
    aliases: ["not at all", "never", "0", "none", "no"],
  },
  {
    id: "likert-1",
    scaleItemId: "gad-1",
    textResponse: "Several days",
    numericValue: 1,
    aliases: ["several days", "sometimes", "1", "few days", "rarely"],
  },
  {
    id: "likert-2",
    scaleItemId: "gad-1",
    textResponse: "More than half the days",
    numericValue: 2,
    aliases: ["more than half the days", "often", "2", "most days", "frequently"],
  },
  {
    id: "likert-3",
    scaleItemId: "gad-1",
    textResponse: "Nearly every day",
    numericValue: 3,
    aliases: ["nearly every day", "always", "3", "daily", "constantly"],
  },
  // Big Five Likert responses (1-5 scale)
  {
    id: "bf-likert-1",
    scaleItemId: "bf-1",
    textResponse: "Strongly disagree",
    numericValue: 1,
    aliases: ["strongly disagree", "1", "completely disagree"],
  },
  {
    id: "bf-likert-2",
    scaleItemId: "bf-1",
    textResponse: "Disagree",
    numericValue: 2,
    aliases: ["disagree", "2", "somewhat disagree"],
  },
  {
    id: "bf-likert-3",
    scaleItemId: "bf-1",
    textResponse: "Neutral",
    numericValue: 3,
    aliases: ["neutral", "3", "neither agree nor disagree", "undecided"],
  },
  {
    id: "bf-likert-4",
    scaleItemId: "bf-1",
    textResponse: "Agree",
    numericValue: 4,
    aliases: ["agree", "4", "somewhat agree"],
  },
  {
    id: "bf-likert-5",
    scaleItemId: "bf-1",
    textResponse: "Strongly agree",
    numericValue: 5,
    aliases: ["strongly agree", "5", "completely agree"],
  },
]
