// lib/seed-scales.ts

const FREQUENCY_OPTIONS = [
  { label: 'Not at all', value: 0, order: 0 },
  { label: 'Several days', value: 1, order: 1 },
  { label: 'More than half the days', value: 2, order: 2 },
  { label: 'Nearly every day', value: 3, order: 3 },
]

export const LIBRARY_SCALES = [
  {
    name: 'PHQ-9',
    description: 'Patient Health Questionnaire — 9-item depression screen',
    isLibrary: true,
    items: [
      { order: 1, text: 'Little interest or pleasure in doing things', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 2, text: 'Feeling down, depressed, or hopeless', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 3, text: 'Trouble falling or staying asleep, or sleeping too much', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 4, text: 'Feeling tired or having little energy', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 5, text: 'Poor appetite or overeating', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 6, text: 'Feeling bad about yourself — or that you are a failure or have let yourself or your family down', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 7, text: 'Trouble concentrating on things, such as reading the newspaper or watching television', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 8, text: 'Moving or speaking so slowly that other people could have noticed — or being so fidgety or restless that you have been moving around a lot more than usual', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 9, text: 'Thoughts that you would be better off dead, or of hurting yourself in some way', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
    ],
    thresholds: [
      { label: 'None–Minimal', minScore: 0, maxScore: 4 },
      { label: 'Mild', minScore: 5, maxScore: 9 },
      { label: 'Moderate', minScore: 10, maxScore: 14 },
      { label: 'Moderately Severe', minScore: 15, maxScore: 19 },
      { label: 'Severe', minScore: 20, maxScore: 27 },
    ],
  },
  {
    name: 'GAD-7',
    description: 'Generalised Anxiety Disorder — 7-item anxiety screen',
    isLibrary: true,
    items: [
      { order: 1, text: 'Feeling nervous, anxious, or on edge', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 2, text: 'Not being able to stop or control worrying', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 3, text: 'Worrying too much about different things', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 4, text: 'Trouble relaxing', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 5, text: 'Being so restless that it is hard to sit still', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 6, text: 'Becoming easily annoyed or irritable', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 7, text: 'Feeling afraid as if something awful might happen', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
    ],
    thresholds: [
      { label: 'Minimal', minScore: 0, maxScore: 4 },
      { label: 'Mild', minScore: 5, maxScore: 9 },
      { label: 'Moderate', minScore: 10, maxScore: 14 },
      { label: 'Severe', minScore: 15, maxScore: 21 },
    ],
  },
  {
    name: 'BDI-II',
    description: 'Beck Depression Inventory — 21-item depression assessment',
    isLibrary: true,
    items: Array.from({ length: 21 }, (_, i) => ({
      order: i + 1,
      text: `BDI-II Item ${i + 1}`,
      type: 'MULTIPLE_CHOICE' as const,
      options: [
        { label: '0', value: 0, order: 0 },
        { label: '1', value: 1, order: 1 },
        { label: '2', value: 2, order: 2 },
        { label: '3', value: 3, order: 3 },
      ],
    })),
    thresholds: [
      { label: 'Minimal', minScore: 0, maxScore: 13 },
      { label: 'Mild', minScore: 14, maxScore: 19 },
      { label: 'Moderate', minScore: 20, maxScore: 28 },
      { label: 'Severe', minScore: 29, maxScore: 63 },
    ],
  },
  {
    name: 'AUDIT',
    description: 'Alcohol Use Disorders Identification Test — 10-item alcohol screen',
    isLibrary: true,
    items: [
      { order: 1, text: 'How often do you have a drink containing alcohol?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Monthly or less', value: 1, order: 1 }, { label: '2–4 times a month', value: 2, order: 2 }, { label: '2–3 times a week', value: 3, order: 3 }, { label: '4+ times a week', value: 4, order: 4 }] },
      { order: 2, text: 'How many drinks containing alcohol do you have on a typical day when you are drinking?', type: 'MULTIPLE_CHOICE', options: [{ label: '1–2', value: 0, order: 0 }, { label: '3–4', value: 1, order: 1 }, { label: '5–6', value: 2, order: 2 }, { label: '7–9', value: 3, order: 3 }, { label: '10+', value: 4, order: 4 }] },
      { order: 3, text: 'How often do you have 6 or more drinks on one occasion?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Less than monthly', value: 1, order: 1 }, { label: 'Monthly', value: 2, order: 2 }, { label: 'Weekly', value: 3, order: 3 }, { label: 'Daily or almost daily', value: 4, order: 4 }] },
      { order: 4, text: 'How often during the last year have you found that you were not able to stop drinking once you had started?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Less than monthly', value: 1, order: 1 }, { label: 'Monthly', value: 2, order: 2 }, { label: 'Weekly', value: 3, order: 3 }, { label: 'Daily or almost daily', value: 4, order: 4 }] },
      { order: 5, text: 'How often during the last year have you failed to do what was normally expected from you because of drinking?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Less than monthly', value: 1, order: 1 }, { label: 'Monthly', value: 2, order: 2 }, { label: 'Weekly', value: 3, order: 3 }, { label: 'Daily or almost daily', value: 4, order: 4 }] },
      { order: 6, text: 'How often during the last year have you needed a first drink in the morning to get yourself going after a heavy drinking session?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Less than monthly', value: 1, order: 1 }, { label: 'Monthly', value: 2, order: 2 }, { label: 'Weekly', value: 3, order: 3 }, { label: 'Daily or almost daily', value: 4, order: 4 }] },
      { order: 7, text: 'How often during the last year have you had a feeling of guilt or remorse after drinking?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Less than monthly', value: 1, order: 1 }, { label: 'Monthly', value: 2, order: 2 }, { label: 'Weekly', value: 3, order: 3 }, { label: 'Daily or almost daily', value: 4, order: 4 }] },
      { order: 8, text: 'How often during the last year have you been unable to remember what happened the night before because you had been drinking?', type: 'MULTIPLE_CHOICE', options: [{ label: 'Never', value: 0, order: 0 }, { label: 'Less than monthly', value: 1, order: 1 }, { label: 'Monthly', value: 2, order: 2 }, { label: 'Weekly', value: 3, order: 3 }, { label: 'Daily or almost daily', value: 4, order: 4 }] },
      { order: 9, text: 'Have you or someone else been injured as a result of your drinking?', type: 'MULTIPLE_CHOICE', options: [{ label: 'No', value: 0, order: 0 }, { label: 'Yes, but not in the last year', value: 2, order: 1 }, { label: 'Yes, during the last year', value: 4, order: 2 }] },
      { order: 10, text: 'Has a relative, friend, doctor, or other health worker been concerned about your drinking or suggested you cut down?', type: 'MULTIPLE_CHOICE', options: [{ label: 'No', value: 0, order: 0 }, { label: 'Yes, but not in the last year', value: 2, order: 1 }, { label: 'Yes, during the last year', value: 4, order: 2 }] },
    ],
    thresholds: [
      { label: 'Low Risk', minScore: 0, maxScore: 7 },
      { label: 'Hazardous', minScore: 8, maxScore: 15 },
      { label: 'Harmful', minScore: 16, maxScore: 19 },
      { label: 'Dependence Likely', minScore: 20, maxScore: 40 },
    ],
  },
  {
    name: 'DASS-21',
    description: 'Depression Anxiety Stress Scales — 21-item measure',
    isLibrary: true,
    items: [
      { order: 1, text: 'I found it hard to wind down', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 2, text: 'I was aware of dryness of my mouth', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 3, text: 'I could not seem to experience any positive feeling at all', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 4, text: 'I experienced breathing difficulty', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 5, text: 'I found it difficult to work up the initiative to do things', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 6, text: 'I tended to over-react to situations', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 7, text: 'I experienced trembling (e.g. in the hands)', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 8, text: 'I felt that I was using a lot of nervous energy', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 9, text: 'I was worried about situations in which I might panic and make a fool of myself', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 10, text: 'I felt that I had nothing to look forward to', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 11, text: 'I found myself getting agitated', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 12, text: 'I found it difficult to relax', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 13, text: 'I felt down-hearted and blue', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 14, text: 'I was intolerant of anything that kept me from getting on with what I was doing', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 15, text: 'I felt I was close to panic', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 16, text: 'I was unable to become enthusiastic about anything', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 17, text: 'I felt I was not worth much as a person', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 18, text: 'I felt that I was rather touchy', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 19, text: 'I was aware of the action of my heart in the absence of physical exertion', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 20, text: 'I felt scared without any good reason', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
      { order: 21, text: 'I felt that life was meaningless', type: 'MULTIPLE_CHOICE', options: FREQUENCY_OPTIONS },
    ],
    thresholds: [
      { label: 'Normal', minScore: 0, maxScore: 14 },
      { label: 'Mild', minScore: 15, maxScore: 28 },
      { label: 'Moderate', minScore: 29, maxScore: 42 },
      { label: 'Severe', minScore: 43, maxScore: 56 },
      { label: 'Extremely Severe', minScore: 57, maxScore: 63 },
    ],
  },
  {
    name: 'PCL-5',
    description: 'PTSD Checklist for DSM-5 — 20-item PTSD screen',
    isLibrary: true,
    items: Array.from({ length: 20 }, (_, i) => ({
      order: i + 1,
      text: `PCL-5 Item ${i + 1}`,
      type: 'MULTIPLE_CHOICE' as const,
      options: [
        { label: 'Not at all', value: 0, order: 0 },
        { label: 'A little bit', value: 1, order: 1 },
        { label: 'Moderately', value: 2, order: 2 },
        { label: 'Quite a bit', value: 3, order: 3 },
        { label: 'Extremely', value: 4, order: 4 },
      ],
    })),
    thresholds: [
      { label: 'Minimal', minScore: 0, maxScore: 20 },
      { label: 'Mild', minScore: 21, maxScore: 32 },
      { label: 'Moderate', minScore: 33, maxScore: 44 },
      { label: 'Severe', minScore: 45, maxScore: 80 },
    ],
  },
]
